# Generated by Django 2.2.4 on 2020-08-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('N', 'Normal'), ('B', 'Baixa'), ('A', 'Alta')], max_length=1),
        ),
    ]
